#!/usr/bin/env python3

import argparse
import datetime


def arg_parse():
    parser = argparse.ArgumentParser(description="fileinput & argparse")
    parser.add_argument('-st', '--stime', default=1,
                        type=float, help='start time from argument')
    parser.add_argument('-et', '--etime', default=5,
                        type=float, help='end time from argument')
    return parser.parse_args()


def main():
    parse = arg_parse()
    start_time = parse.stime
    end_time = parse.etime

    timer = datetime.timedelta(seconds=60*end_time) - \
        datetime.timedelta(seconds=start_time)
    timer = str(timer).split(":")
    print(" "+timer[1] + ":" + timer[2])


main()
